//////////////////////////////////////////////////////////////////////////////
// Model: pelican.qm
// File:  ./bsp.h
//
// This file has been generated automatically by QP Modeler (QM).
// DO NOT EDIT THIS FILE MANUALLY.
//
// Please visit www.state-machine.com/qm for more information.
//////////////////////////////////////////////////////////////////////////////
#ifndef bsp_h
#define bsp_h

#include <avr/io.h>  // AVR I/O

// Sys timer tick per seconds
#define BSP_TICKS_PER_SEC    100

// street signals ...
enum BSP_CarsSignal {
    CARS_BLANK, CARS_RED, CARS_YELLOW, CARS_GREEN
};

enum BSP_PedsSignal {
    PEDS_BLANK, PEDS_DONT_WALK, PEDS_WALK
};

void BSP_init(void);
void BSP_signalCars(enum BSP_CarsSignal sig);
void BSP_signalPeds(enum BSP_PedsSignal sig);
void BSP_showState (char const *state);

/////////////////////////////////////////////////////////////////////
// NOTE: The CPU clock frequency F_CPU is defined externally for each
// Arduino board

#endif  // bsp_h
