//////////////////////////////////////////////////////////////////////////////
// Model: pelican.qm
// File:  ./pelican.h
//
// This file has been generated automatically by QP Modeler (QM).
// DO NOT EDIT THIS FILE MANUALLY.
//
// Please visit www.state-machine.com/qm for more information.
//////////////////////////////////////////////////////////////////////////////
#ifndef pelican_h
#define pelican_h

enum PelicanSignals {
    PEDS_WAITING_SIG = Q_USER_SIG,
    MAX_PUB_SIG,  // the last published signal

    ON_SIG,
    OFF_SIG,
    TIMEOUT_SIG,
};

// active objects ..................................................
extern QActive * const AO_Pelican;   // "opaque" pointer to Pelican AO

#endif // pelican_h
